10.10.2025 Update

diff --git a/pacstrap_bak b/pacstrap_bak
--- a/pacstrap_bak
+++ b/pacstrap_bak
@@ -1,4 +1,5 @@
 #!/bin/bash
+# SPDX-License-Identifier: GPL-2.0-only
 
 #
 # Assumptions:
@@ -10,98 +11,29 @@
 
 shopt -s extglob
 
-# generated from util-linux source: libmount/src/utils.c
-declare -A pseudofs_types=([anon_inodefs]=1
-                           [apparmorfs]=1
-                           [autofs]=1
-                           [bdev]=1
-                           [binder]=1
-                           [binfmt_misc]=1
-                           [bpf]=1
-                           [cgroup]=1
-                           [cgroup2]=1
-                           [configfs]=1
-                           [cpuset]=1
-                           [debugfs]=1
-                           [devfs]=1
-                           [devpts]=1
-                           [devtmpfs]=1
-                           [dlmfs]=1
-                           [dmabuf]=1
-                           [drm]=1
-                           [efivarfs]=1
-                           [fuse]=1
-                           [fuse.archivemount]=1
-                           [fuse.avfsd]=1
-                           [fuse.dumpfs]=1
-                           [fuse.encfs]=1
-                           [fuse.gvfs-fuse-daemon]=1
-                           [fuse.gvfsd-fuse]=1
-                           [fuse.lxcfs]=1
-                           [fuse.rofiles-fuse]=1
-                           [fuse.vmware-vmblock]=1
-                           [fuse.xwmfs]=1
-                           [fusectl]=1
-                           [hugetlbfs]=1
-                           [ipathfs]=1
-                           [mqueue]=1
-                           [nfsd]=1
-                           [none]=1
-                           [nsfs]=1
-                           [overlay]=1
-                           [pipefs]=1
-                           [proc]=1
-                           [pstore]=1
-                           [ramfs]=1
-                           [resctrl]=1
-                           [rootfs]=1
-                           [rpc_pipefs]=1
-                           [securityfs]=1
-                           [selinuxfs]=1
-                           [smackfs]=1
-                           [sockfs]=1
-                           [spufs]=1
-                           [sysfs]=1
-                           [tmpfs]=1
-                           [tracefs]=1
-                           [vboxsf]=1
-                           [virtiofs]=1)
+hostcache=0
+copykeyring=1
+initkeyring=0
+copymirrorlist=1
+pacman_args=()
+pacmode=-Sy
+unshare=0
+copyconf=0
+pacman_config=/etc/pacman.conf
 
-# generated from: pkgfile -vbr '/fsck\..+' | awk -F. '{ print $NF }' | sort
-declare -A fsck_types=([btrfs]=0    # btrfs doesn't need a regular fsck utility
-                       [cramfs]=1
-                       [erofs]=1
-                       [exfat]=1
-                       [ext2]=1
-                       [ext3]=1
-                       [ext4]=1
-                       [f2fs]=1
-                       [fat]=1
-                       [jfs]=1
-                       [minix]=1
-                       [msdos]=1
-                       [reiserfs]=1
-                       [vfat]=1
-                       [xfs]=1)
+#!/hint/bash
+# SPDX-License-Identifier: GPL-2.0-only
+# shellcheck disable=SC2059 # $1 and $2 can contain the printf modifiers
 
 out() { printf "$1 $2\n" "${@:3}"; }
 error() { out "==> ERROR:" "$@"; } >&2
 warning() { out "==> WARNING:" "$@"; } >&2
 msg() { out "==>" "$@"; }
-msg2() { out "  ->" "$@";}
 die() { error "$@"; exit 1; }
 
 ignore_error() {
   "$@" 2>/dev/null
   return 0
-}
-
-in_array() {
-  local i
-  for i in "${@:2}"; do
-    [[ $1 = "$i" ]] && return 0
-  done
-  return 1
 }
 
 chroot_add_mount() {
@@ -119,6 +51,16 @@ chroot_setup() {
   CHROOT_ACTIVE_MOUNTS=()
   [[ $(trap -p EXIT) ]] && die '(BUG): attempting to overwrite existing EXIT trap'
   trap 'chroot_teardown' EXIT
+
+  chroot_add_mount proc "$1/proc" -t proc -o nosuid,noexec,nodev &&
+  chroot_add_mount sys "$1/sys" -t sysfs -o nosuid,noexec,nodev,ro &&
+  ignore_error chroot_maybe_add_mount "[[ -d '$1/sys/firmware/efi/efivars' ]]" \
+      efivarfs "$1/sys/firmware/efi/efivars" -t efivarfs -o nosuid,noexec,nodev &&
+  chroot_add_mount udev "$1/dev" -t devtmpfs -o mode=0755,nosuid &&
+  chroot_add_mount devpts "$1/dev/pts" -t devpts -o mode=0620,gid=5,nosuid,noexec &&
+  chroot_add_mount shm "$1/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev &&
+  chroot_add_mount /run "$1/run" --bind --make-private &&
+  chroot_add_mount tmp "$1/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
 }
 
 chroot_teardown() {
@@ -134,7 +76,7 @@ chroot_add_mount_lazy() {
 
 chroot_bind_device() {
   touch "$2" && CHROOT_ACTIVE_FILES=("$2" "${CHROOT_ACTIVE_FILES[@]}")
-  chroot_add_mount $1 "$2" --bind
+  chroot_add_mount "$1" "$2" --bind
 }
 
 chroot_add_link() {
@@ -151,10 +93,10 @@ unshare_setup() {
   chroot_add_mount_lazy "$1" "$1" --bind &&
   chroot_add_mount proc "$1/proc" -t proc -o nosuid,noexec,nodev &&
   chroot_add_mount_lazy /sys "$1/sys" --rbind &&
-  chroot_add_link "$1/proc/self/fd" "$1/dev/fd" &&
-  chroot_add_link "$1/proc/self/fd/0" "$1/dev/stdin" &&
-  chroot_add_link "$1/proc/self/fd/1" "$1/dev/stdout" &&
-  chroot_add_link "$1/proc/self/fd/2" "$1/dev/stderr" &&
+  chroot_add_link /proc/self/fd "$1/dev/fd" &&
+  chroot_add_link /proc/self/fd/0 "$1/dev/stdin" &&
+  chroot_add_link /proc/self/fd/1 "$1/dev/stdout" &&
+  chroot_add_link /proc/self/fd/2 "$1/dev/stderr" &&
   chroot_bind_device /dev/full "$1/dev/full" &&
   chroot_bind_device /dev/null "$1/dev/null" &&
   chroot_bind_device /dev/random "$1/dev/random" &&
@@ -199,172 +141,6 @@ declare_all() {
   declare -pf
 }
 
-try_cast() (
-  _=$(( $1#$2 ))
-) 2>/dev/null
-
-valid_number_of_base() {
-  local base=$1 len=${#2} i=
-
-  for (( i = 0; i < len; i++ )); do
-    try_cast "$base" "${2:i:1}" || return 1
-  done
-
-  return 0
-}
-
-mangle() {
-  local i= chr= out=
-  local {a..f}= {A..F}=
-
-  for (( i = 0; i < ${#1}; i++ )); do
-    chr=${1:i:1}
-    case $chr in
-      [[:space:]\\])
-        printf -v chr '%03o' "'$chr"
-        out+=\\
-        ;;
-    esac
-    out+=$chr
-  done
-
-  printf '%s' "$out"
-}
-
-unmangle() {
-  local i= chr= out= len=$(( ${#1} - 4 ))
-  local {a..f}= {A..F}=
-
-  for (( i = 0; i < len; i++ )); do
-    chr=${1:i:1}
-    case $chr in
-      \\)
-        if valid_number_of_base 8 "${1:i+1:3}" ||
-            valid_number_of_base 16 "${1:i+1:3}"; then
-          printf -v chr '%b' "${1:i:4}"
-          (( i += 3 ))
-        fi
-        ;;
-    esac
-    out+=$chr
-  done
-
-  printf '%s' "$out${1:i}"
-}
-
-optstring_match_option() {
-  local candidate pat patterns
-
-  IFS=, read -ra patterns <<<"$1"
-  for pat in "${patterns[@]}"; do
-    if [[ $pat = *=* ]]; then
-      # "key=val" will only ever match "key=val"
-      candidate=$2
-    else
-      # "key" will match "key", but also "key=anyval"
-      candidate=${2%%=*}
-    fi
-
-    [[ $pat = "$candidate" ]] && return 0
-  done
-
-  return 1
-}
-
-optstring_remove_option() {
-  local o options_ remove=$2 IFS=,
-
-  read -ra options_ <<<"${!1}"
-
-  for o in "${!options_[@]}"; do
-    optstring_match_option "$remove" "${options_[o]}" && unset 'options_[o]'
-  done
-
-  declare -g "$1=${options_[*]}"
-}
-
-optstring_normalize() {
-  local o options_ norm IFS=,
-
-  read -ra options_ <<<"${!1}"
-
-  # remove empty fields
-  for o in "${options_[@]}"; do
-    [[ $o ]] && norm+=("$o")
-  done
-
-  # avoid empty strings, reset to "defaults"
-  declare -g "$1=${norm[*]:-defaults}"
-}
-
-optstring_append_option() {
-  if ! optstring_has_option "$1" "$2"; then
-    declare -g "$1=${!1},$2"
-  fi
-
-  optstring_normalize "$1"
-}
-
-optstring_prepend_option() {
-  local options_=$1
-
-  if ! optstring_has_option "$1" "$2"; then
-    declare -g "$1=$2,${!1}"
-  fi
-
-  optstring_normalize "$1"
-}
-
-optstring_get_option() {
-  local opts o
-
-  IFS=, read -ra opts <<<"${!1}"
-  for o in "${opts[@]}"; do
-    if optstring_match_option "$2" "$o"; then
-      declare -g "$o"
-      return 0
-    fi
-  done
-
-  return 1
-}
-
-optstring_has_option() {
-  local "${2%%=*}"
-
-  optstring_get_option "$1" "$2"
-}
-
-dm_name_for_devnode() {
-  read dm_name <"/sys/class/block/${1#/dev/}/dm/name"
-  if [[ $dm_name ]]; then
-    printf '/dev/mapper/%s' "$dm_name"
-  else
-    # don't leave the caller hanging, just print the original name
-    # along with the failure.
-    error 'Failed to resolve device mapper name for: %s' "$1"
-  fi
-}
-
-fstype_is_pseudofs() {
-  (( pseudofs_types["$1"] ))
-}
-
-fstype_has_fsck() {
-  (( fsck_types["$1"] ))
-}
-
-
-hostcache=0
-copykeyring=1
-initkeyring=0
-copymirrorlist=1
-pacman_args=()
-pacmode=-Sy
-setup=chroot_setup
-unshare=0
-copyconf=0
-pacman_config=/etc/pacman.conf
 
 usage() {
   cat <<EOF
@@ -388,6 +164,45 @@ pacstrap installs packages to the specified new root directory. If no packages
 are given, pacstrap defaults to the "base" group.
 
 EOF
+}
+
+pacstrap() {
+  (( EUID == 0 )) || die 'This script must be run with root privileges'
+
+  # create obligatory directories
+  msg 'Creating install root at %s' "$newroot"
+  # shellcheck disable=SC2174 # permissions are perfectly fine here
+  mkdir -m 0755 -p "$newroot"/var/{cache/pacman/pkg,lib/pacman,log} "$newroot"/{dev,run,etc/pacman.d}
+  # shellcheck disable=SC2174 # permissions are perfectly fine here
+  mkdir -m 1777 -p "$newroot"/tmp
+  # shellcheck disable=SC2174 # permissions are perfectly fine here
+  mkdir -m 0555 -p "$newroot"/{sys,proc}
+
+  # mount API filesystems
+  $setup "$newroot" || die "failed to setup chroot %s" "$newroot"
+
+  if [[ ! -d $newroot/etc/pacman.d/gnupg ]]; then
+    if (( initkeyring )); then
+      pacman-key --gpgdir "$newroot"/etc/pacman.d/gnupg --init
+    elif (( copykeyring )) && [[ -d /etc/pacman.d/gnupg ]]; then
+      # if there's a keyring on the host, copy it into the new root
+      cp -a --no-preserve=ownership /etc/pacman.d/gnupg "$newroot/etc/pacman.d/"
+    fi
+  fi
+
+  msg 'Installing packages to %s' "$newroot"
+  if ! $pid_unshare pacman -r "$newroot" "${pacman_args[@]}"; then
+    die 'Failed to install packages to new root'
+  fi
+
+  if (( copymirrorlist )); then
+    # install the host's mirrorlist onto the new root
+    cp -a /etc/pacman.d/mirrorlist "$newroot/etc/pacman.d/"
+  fi
+
+  if (( copyconf )); then
+    cp -a "$pacman_config" "$newroot/etc/pacman.conf"
+  fi
 }
 
 if [[ -z $1 || $1 = @(-h|--help) ]]; then
@@ -419,7 +234,6 @@ while getopts ':C:cDGiKMNPU' flag; do
       copymirrorlist=0
       ;;
     N)
-      setup=unshare_setup
       unshare=1
       ;;
     P)
@@ -439,8 +253,17 @@ done
 shift $(( OPTIND - 1 ))
 
 (( $# )) || die "No root directory specified"
-newroot=$1; shift
-pacman_args+=("$pacmode" "${@:-base}" --config="$pacman_config")
+newroot=$1
+shift
+
+[[ -d $newroot ]] || die "%s is not a directory" "$newroot"
+
+tmpfile="$(mktemp -t pacman.conf.XXXX)"
+cp "$pacman_config" "$tmpfile"
+sed -i 's/^DownloadUser/#&/' "$tmpfile"
+pacman_config="$tmpfile"
+
+pacman_args+=("$pacmode" "${@:-base}" --config="$pacman_config" --disable-sandbox)
 
 if (( ! hostcache )); then
   pacman_args+=(--cachedir="$newroot/var/cache/pacman/pkg")
@@ -450,48 +273,14 @@ if (( ! interactive )); then
   pacman_args+=(--noconfirm)
 fi
 
-[[ -d $newroot ]] || die "%s is not a directory" "$newroot"
-
-pacstrap() {
-  (( EUID == 0 )) || die 'This script must be run with root privileges'
-
-  # create obligatory directories
-  msg 'Creating install root at %s' "$newroot"
-  mkdir -m 0755 -p "$newroot"/var/{cache/pacman/pkg,lib/pacman,log} "$newroot"/{dev,run,etc/pacman.d}
-  mkdir -m 1777 -p "$newroot"/tmp
-  mkdir -m 0555 -p "$newroot"/{sys,proc}
-
-  # mount API filesystems
-  $setup "$newroot" || die "failed to setup chroot %s" "$newroot"
-
-  if [[ ! -d $newroot/etc/pacman.d/gnupg ]]; then
-    if (( initkeyring )); then
-      pacman-key --gpgdir "$newroot"/etc/pacman.d/gnupg --init
-    elif (( copykeyring )) && [[ -d /etc/pacman.d/gnupg ]]; then
-      # if there's a keyring on the host, copy it into the new root
-      cp -a --no-preserve=ownership /etc/pacman.d/gnupg "$newroot/etc/pacman.d/"
-    fi
-  fi
-
-  msg 'Installing packages to %s' "$newroot"
-  if ! $pid_unshare pacman -r "$newroot" "${pacman_args[@]}"; then
-    die 'Failed to install packages to new root'
-  fi
-
-  if (( copymirrorlist )); then
-    # install the host's mirrorlist onto the new root
-    cp -a /etc/pacman.d/mirrorlist "$newroot/etc/pacman.d/"
-  fi
-
-  if (( copyconf )); then
-    cp -a "$pacman_config" "$newroot/etc/pacman.conf"
-  fi
-}
-
 if (( unshare )); then
+  setup=unshare_setup
   $mount_unshare bash -c "$(declare_all); pacstrap"
 else
+  setup=chroot_setup
   pacstrap
 fi
 
-# vim: et ts=2 sw=2 ft=sh:
+# TODO: There is a trap check on exit. Need to rework the trap handling with
+# hook-ins/callbacks to remove aux files
+rm "$tmpfile"
