11.01.2023 Update

diff --git a/pacstrap_bak b/pacstrap_bak
--- a/pacstrap_bak
+++ b/pacstrap_bak
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-# auto mount removed since calamares already does the job, pacstrap-old get error "/proc already mounted" for example.
-
 #
 # Assumptions:
 #  1) User has partitioned, formatted, and mounted partitions on /mnt
@@ -14,10 +12,12 @@ shopt -s extglob
 
 # generated from util-linux source: libmount/src/utils.c
 declare -A pseudofs_types=([anon_inodefs]=1
+                           [apparmorfs]=1
                            [autofs]=1
                            [bdev]=1
-                           [bpf]=1
+                           [binder]=1
                            [binfmt_misc]=1
+                           [bpf]=1
                            [cgroup]=1
                            [cgroup2]=1
                            [configfs]=1
@@ -27,32 +27,56 @@ declare -A pseudofs_types=([anon_inodefs]=1
                            [devpts]=1
                            [devtmpfs]=1
                            [dlmfs]=1
+                           [dmabuf]=1
+                           [drm]=1
                            [efivarfs]=1
+                           [fuse]=1
+                           [fuse.archivemount]=1
+                           [fuse.avfsd]=1
+                           [fuse.dumpfs]=1
+                           [fuse.encfs]=1
                            [fuse.gvfs-fuse-daemon]=1
+                           [fuse.gvfsd-fuse]=1
+                           [fuse.lxcfs]=1
+                           [fuse.rofiles-fuse]=1
+                           [fuse.vmware-vmblock]=1
+                           [fuse.xwmfs]=1
                            [fusectl]=1
                            [hugetlbfs]=1
+                           [ipathfs]=1
                            [mqueue]=1
                            [nfsd]=1
                            [none]=1
+                           [nsfs]=1
+                           [overlay]=1
                            [pipefs]=1
                            [proc]=1
                            [pstore]=1
                            [ramfs]=1
+                           [resctrl]=1
                            [rootfs]=1
                            [rpc_pipefs]=1
                            [securityfs]=1
+                           [selinuxfs]=1
+                           [smackfs]=1
                            [sockfs]=1
                            [spufs]=1
                            [sysfs]=1
-                           [tmpfs]=1)
+                           [tmpfs]=1
+                           [tracefs]=1
+                           [vboxsf]=1
+                           [virtiofs]=1)
 
 # generated from: pkgfile -vbr '/fsck\..+' | awk -F. '{ print $NF }' | sort
-declare -A fsck_types=([cramfs]=1
+declare -A fsck_types=([btrfs]=0    # btrfs doesn't need a regular fsck utility
+                       [cramfs]=1
+                       [erofs]=1
                        [exfat]=1
                        [ext2]=1
                        [ext3]=1
                        [ext4]=1
-                       [ext4dev]=1
+                       [f2fs]=1
+                       [fat]=1
                        [jfs]=1
                        [minix]=1
                        [msdos]=1
@@ -96,6 +120,7 @@ chroot_setup() {
   [[ $(trap -p EXIT) ]] && die '(BUG): attempting to overwrite existing EXIT trap'
   trap 'chroot_teardown' EXIT
 
+  chroot_add_mount run "$1/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
 }
 
 chroot_teardown() {
@@ -103,6 +128,75 @@ chroot_teardown() {
     umount "${CHROOT_ACTIVE_MOUNTS[@]}"
   fi
   unset CHROOT_ACTIVE_MOUNTS
+}
+
+chroot_add_mount_lazy() {
+  mount "$@" && CHROOT_ACTIVE_LAZY=("$2" "${CHROOT_ACTIVE_LAZY[@]}")
+}
+
+chroot_bind_device() {
+  touch "$2" && CHROOT_ACTIVE_FILES=("$2" "${CHROOT_ACTIVE_FILES[@]}")
+  chroot_add_mount $1 "$2" --bind
+}
+
+chroot_add_link() {
+  ln -sf "$1" "$2" && CHROOT_ACTIVE_FILES=("$2" "${CHROOT_ACTIVE_FILES[@]}")
+}
+
+unshare_setup() {
+  CHROOT_ACTIVE_MOUNTS=()
+  CHROOT_ACTIVE_LAZY=()
+  CHROOT_ACTIVE_FILES=()
+  [[ $(trap -p EXIT) ]] && die '(BUG): attempting to overwrite existing EXIT trap'
+  trap 'unshare_teardown' EXIT
+
+  chroot_add_mount_lazy "$1" "$1" --bind &&
+  chroot_add_mount_lazy /sys "$1/sys" --rbind &&
+  chroot_add_link "$1/proc/self/fd" "$1/dev/fd" &&
+  chroot_add_link "$1/proc/self/fd/0" "$1/dev/stdin" &&
+  chroot_add_link "$1/proc/self/fd/1" "$1/dev/stdout" &&
+  chroot_add_link "$1/proc/self/fd/2" "$1/dev/stderr" &&
+  chroot_bind_device /dev/full "$1/dev/full" &&
+  chroot_bind_device /dev/null "$1/dev/null" &&
+  chroot_bind_device /dev/random "$1/dev/random" &&
+  chroot_bind_device /dev/tty "$1/dev/tty" &&
+  chroot_bind_device /dev/urandom "$1/dev/urandom" &&
+  chroot_bind_device /dev/zero "$1/dev/zero" &&
+  chroot_add_mount run "$1/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
+}
+
+unshare_teardown() {
+  chroot_teardown
+
+  if (( ${#CHROOT_ACTIVE_LAZY[@]} )); then
+    umount --lazy "${CHROOT_ACTIVE_LAZY[@]}"
+  fi
+  unset CHROOT_ACTIVE_LAZY
+
+  if (( ${#CHROOT_ACTIVE_FILES[@]} )); then
+    rm "${CHROOT_ACTIVE_FILES[@]}"
+  fi
+  unset CHROOT_ACTIVE_FILES
+}
+
+pid_unshare="unshare --fork --pid"
+mount_unshare="$pid_unshare --mount --map-auto --map-root-user --setuid 0 --setgid 0"
+
+# This outputs code for declaring all variables to stdout. For example, if
+# FOO=BAR, then running
+#     declare -p FOO
+# will result in the output
+#     declare -- FOO="bar"
+# This function may be used to re-declare all currently used variables and
+# functions in a new shell.
+declare_all() {
+  # Remove read-only variables to avoid warnings. Unfortunately, declare +r -p
+  # doesn't work like it looks like it should (declaring only read-write
+  # variables). However, declare -rp will print out read-only variables, which
+  # we can then use to remove those definitions.
+  declare -p | grep -Fvf <(declare -rp)
+  # Then declare functions
+  declare -pf
 }
 
 try_cast() (
@@ -248,7 +342,6 @@ dm_name_for_devnode() {
   else
     # don't leave the caller hanging, just print the original name
     # along with the failure.
-    print '%s' "$1"
     error 'Failed to resolve device mapper name for: %s' "$1"
   fi
 }
@@ -264,20 +357,36 @@ fstype_has_fsck() {
 
 hostcache=0
 copykeyring=1
+initkeyring=0
 copymirrorlist=1
+pacman_args=()
+pacmode=-Sy
+setup=chroot_setup
+unshare=0
+copyconf=0
+pacman_config=/etc/pacman.conf
 
 usage() {
   cat <<EOF
 usage: ${0##*/} [options] root [packages...]
+
   Options:
     -C <config>    Use an alternate config file for pacman
     -c             Use the package cache on the host, rather than the target
+    -D             Skip pacman dependency checks
     -G             Avoid copying the host's pacman keyring to the target
     -i             Prompt for package confirmation when needed (run interactively)
+    -K             Initialize an empty pacman keyring in the target (implies '-G')
     -M             Avoid copying the host's mirrorlist to the target
+    -N             Run in unshare mode as a regular user
+    -P             Copy the host's pacman config to the target
+    -U             Use pacman -U to install packages
+
     -h             Print this help message
+
 pacstrap installs packages to the specified new root directory. If no packages
 are given, pacstrap defaults to the "base" group.
+
 EOF
 }
 
@@ -286,15 +395,13 @@ if [[ -z $1 || $1 = @(-h|--help) ]]; then
   exit $(( $# ? 0 : 1 ))
 fi
 
-(( EUID == 0 )) || die 'This script must be run with root privileges'
-
-while getopts ':C:cdGiM' flag; do
+while getopts ':C:cDGiKMNPU' flag; do
   case $flag in
     C)
       pacman_config=$OPTARG
       ;;
-    d)
-      # retired flag. does nothing.
+    D)
+      pacman_args+=(-dd)
       ;;
     c)
       hostcache=1
@@ -305,8 +412,21 @@ while getopts ':C:cdGiM' flag; do
     G)
       copykeyring=0
       ;;
+    K)
+      initkeyring=1
+      ;;
     M)
       copymirrorlist=0
+      ;;
+    N)
+      setup=unshare_setup
+      unshare=1
+      ;;
+    P)
+      copyconf=1
+      ;;
+    U)
+      pacmode=-U
       ;;
     :)
       die '%s: option requires an argument -- '\''%s'\' "${0##*/}" "$OPTARG"
@@ -320,7 +440,7 @@ shift $(( OPTIND - 1 ))
 
 (( $# )) || die "No root directory specified"
 newroot=$1; shift
-pacman_args=("${@:-base}")
+pacman_args+=("$pacmode" "${@:-base}" --config="$pacman_config")
 
 if (( ! hostcache )); then
   pacman_args+=(--cachedir="$newroot/var/cache/pacman/pkg")
@@ -330,23 +450,48 @@ if (( ! interactive )); then
   pacman_args+=(--noconfirm)
 fi
 
-if [[ $pacman_config ]]; then
-  pacman_args+=(--config="$pacman_config")
-fi
-
 [[ -d $newroot ]] || die "%s is not a directory" "$newroot"
 
-# create obligatory directories
-msg 'Creating install root at %s' "$newroot"
-mkdir -m 0755 -p "$newroot"/var/{cache/pacman/pkg,lib/pacman,log} "$newroot"/{dev,run,etc/pacman.d}
-mkdir -m 1777 -p "$newroot"/tmp
-mkdir -m 0555 -p "$newroot"/{sys,proc}
+pacstrap() {
+  (( EUID == 0 )) || die 'This script must be run with root privileges'
 
-# mount API filesystems
-chroot_setup "$newroot" || die "failed to setup chroot %s" "$newroot"
+  # create obligatory directories
+  msg 'Creating install root at %s' "$newroot"
+  mkdir -m 0755 -p "$newroot"/var/{cache/pacman/pkg,lib/pacman,log} "$newroot"/{dev,run,etc/pacman.d}
+  mkdir -m 1777 -p "$newroot"/tmp
+  mkdir -m 0555 -p "$newroot"/{sys,proc}
 
+  # mount API filesystems
+  $setup "$newroot" || die "failed to setup chroot %s" "$newroot"
 
-msg 'Installing packages to %s' "$newroot"
-if ! pacman -r "$newroot" -Sy "${pacman_args[@]}"; then
-  die 'Failed to install packages to new root'
+  if [[ ! -d $newroot/etc/pacman.d/gnupg ]]; then
+    if (( initkeyring )); then
+      pacman-key --gpgdir "$newroot"/etc/pacman.d/gnupg --init
+    elif (( copykeyring )) && [[ -d /etc/pacman.d/gnupg ]]; then
+      # if there's a keyring on the host, copy it into the new root
+      cp -a --no-preserve=ownership /etc/pacman.d/gnupg "$newroot/etc/pacman.d/"
+    fi
+  fi
+
+  msg 'Installing packages to %s' "$newroot"
+  if ! $pid_unshare pacman -r "$newroot" "${pacman_args[@]}"; then
+    die 'Failed to install packages to new root'
+  fi
+
+  if (( copymirrorlist )); then
+    # install the host's mirrorlist onto the new root
+    cp -a /etc/pacman.d/mirrorlist "$newroot/etc/pacman.d/"
+  fi
+
+  if (( copyconf )); then
+    cp -a "$pacman_config" "$newroot/etc/pacman.conf"
+  fi
+}
+
+if (( unshare )); then
+  $mount_unshare bash -c "$(declare_all); pacstrap"
+else
+  pacstrap
 fi
+
+# vim: et ts=2 sw=2 ft=sh:
